/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        extend: {
            "colors": {
                "inverse-surface": "#e6e0e9",
                "secondary-fixed": "#e9ddff",
                "on-tertiary-fixed": "#241a00",
                "on-tertiary-fixed-variant": "#594400",
                "surface-container-highest": "#36343a",
                "on-primary-fixed-variant": "#4f378a",
                "surface-container-high": "#2b292f",
                "on-tertiary": "#3e2e00",
                "on-secondary-fixed": "#1f1635",
                "on-secondary-container": "#bfb2da",
                "tertiary": "#e7c365",
                "surface-dim": "#141218",
                "tertiary-fixed-dim": "#e7c365",
                "primary-fixed": "#e9ddff",
                "on-tertiary-container": "#503d00",
                "surface-tint": "#cfbcff",
                "on-primary-fixed": "#22005d",
                "inverse-on-surface": "#322f35",
                "on-primary": "#381e72",
                "inverse-primary": "#6750a4",
                "primary": "#cfbcff",
                "secondary": "#cdc0e9",
                "surface": "#141218",
                "surface-bright": "#3b383e",
                "surface-variant": "#36343a",
                "on-error": "#690005",
                "secondary-container": "#4d4465",
                "surface-container-low": "#1d1b20",
                "on-primary-container": "#e0d2ff",
                "surface-container-lowest": "#0f0d13",
                "error": "#ffb4ab",
                "on-error-container": "#ffdad6",
                "background": "#141218",
                "outline-variant": "#494551",
                "primary-fixed-dim": "#cfbcff",
                "tertiary-fixed": "#ffdf93",
                "on-surface-variant": "#cbc4d2",
                "on-secondary-fixed-variant": "#4b4263",
                "outline": "#948e9c",
                "secondary-fixed-dim": "#cdc0e9",
                "tertiary-container": "#c9a74d",
                "primary-container": "#6750a4",
                "error-container": "#93000a",
                "surface-container": "#211f24",
                "on-secondary": "#342b4b",
                "on-surface": "#e6e0e9",
                "on-background": "#e6e0e9"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "md": "16px",
                "xl": "48px",
                "xs": "4px",
                "base": "4px",
                "lg": "24px",
                "container-margin": "32px",
                "sm": "8px",
                "gutter": "16px"
            },
            "fontFamily": {
                "headline-lg": ["Inter", "sans-serif"],
                "body-lg": ["Inter", "sans-serif"],
                "label-bold": ["Inter", "sans-serif"],
                "headline-md": ["Inter", "sans-serif"],
                "display": ["Inter", "sans-serif"],
                "label-muted": ["Inter", "sans-serif"],
                "body-sm": ["Inter", "sans-serif"],
                "body-md": ["Inter", "sans-serif"],
                "headline-sm": ["Inter", "sans-serif"]
            },
            "fontSize": {
                "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "label-bold": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
                "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
                "display": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "label-muted": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
                "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }]
            }
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries')
    ],
}
